### ISSUE TITLE
Optimization in ddfSchema generation

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#65]
Semio said:
>on ddfSchema code: it's mostly the same, I think the main difference is that your pseudo code will loop though all values in a column, while I make it calculate the unique values in a column first, and then loop though these unique values. This should improve the speed

Jasper's reply:

```
geo name      is--city 
sgp Singapore TRUE
ukr Ukraine   FALSE

gender name is--nonbinary
male   Male FALSE
demi   Demi TRUE

geo gender population
sgp male   10
ukr male   10
ukr demi   1
```

The above should NOT lead to ddfSchema-object with
`<city, nonbinary>, population`

Unique values in the datapoints:

```
geo:    city, geo
gender: gender, nonbinary
```

The permutations of the unique values:
```
city   , gender   , population
geo    , gender   , population
city   , nonbinary, population
geo    , nonbinary, population
```

`<city,nonbinary>,population` is in there, while it is not in the data

Is this the way you optimized it or in a different way?

**Comment by semio** [comment]
follow up:

Semio Zheng [1:10 AM] 
yes, you are right, consider unique value of a column is not correct.

[1:11] 
as least I should consider the unique combinations of all entity columns, right?

[1:13] 
I will take care of this tomorrow, have to get some sleep now : )

Jasper Heeffer [1:22 AM] 
Yeah, indeed. Combinations of entity columns combined. Non-entity columns can be skipped (edited)

[1:24] 
Also: when you know a file contains all permutations of sets for the entity concepts in the file's primary key, you can stop iterating too (edited)


Jasper Heeffer [1:31 AM] 
E.g. in the example above, if you find that there is <city, nonbinary>, then you can already stop

[1:32] 
Because you know you won't find any other schemas: you have found all possible schemas. (edited)

Jasper Heeffer [1:38 AM] 
If there also was a country set in geo you'd also need <country, gender>
